[package]
name = "relayer"
version = "0.4.1"
authors = ["Justin Kilpatrick <justin@althea.net>"]
edition = "2018"

[lib]
name = "relayer"
path = "src/lib.rs"

[[bin]]
name = "relayer"
path = "src/main.rs"

[dependencies]
ethereum_gravity = { path = "../ethereum_gravity" }
cosmos_gravity = { path = "../cosmos_gravity" }
gravity_abi = { path = "../gravity_abi" }
gravity_utils = { path = "../gravity_utils" }
gravity_proto = { path = "../gravity_proto" }

deep_space = "2.4.7"
ethers = { git = "https://github.com/iqlusioninc/ethers-rs.git", branch = "zaki/error_abi_support", features = ["abigen"] }
serde_derive = "1.0"
clarity = "0.4.11"
docopt = "1"
serde = "1.0"
actix-rt = "2.5"
lazy_static = "1"
web30 = "0.15"
log = "0.4"
env_logger = "0.8"
tokio = { version = "1.4", features = ["fs"] }
tonic = "0.4"
openssl-probe = "0.1"
serde_json = "1.0.68"
reqwest = "0.11.10"

[dev-dependencies]
actix = "0.12"

[features]
ethermint = ["cosmos_gravity/ethermint"]
